---
- name: "Create Azure resources"
  connection: local
  hosts: localhost
  
  tasks:
    - name: load vars from vars/vmvars
      ansible.builtin.include_vars:
        file: ./vars/vmvars

    - name: "Create {{project_prefix}}-rg Resource Group"
      azure_rm_resourcegroup:
        name: "{{resourcegroup_name}}"
        location: "{{location}}"

    - name: "Create {{availabilityset_name}} Availability Set"
      azure_rm_availabilityset:
        name: "{{availabilityset_name}}"
        location: "{{location}}"
        resource_group: "{{resourcegroup_name}}"
        sku: Aligned

    - name: "Create {{virtualnetwork_name}} Virtual Network"
      azure_rm_virtualnetwork:
        name: "{{virtualnetwork_name}}"
        resource_group: "{{resourcegroup_name}}"
        address_prefixes_cidr:
          - "{{virtualnetwork_cidr}}"

    - name: "create {{subnet_name}} Subnet in {{virtualnetwork_name}} for VMs"
      azure_rm_subnet:
        name: "{{subnet_name}}"
        virtual_network_name: "{{virtualnetwork_name}}"
        resource_group: "{{resourcegroup_name}}"
        address_prefix_cidr: "{{subnet_cidr}}"
      register: subnet

    - name: "Create {{securitygroup_name}} security rules (if local IP address was given)"
      azure_rm_securitygroup:
        name: "{{securitygroup_name}}"
        resource_group: "{{resourcegroup_name}}"
        purge_rules: yes
        rules:
          - name: 'AllowSSHFromYourOwnInternetIP'
            protocol: 'Tcp'
            source_address_prefix: "{{local_ip}}"
            destination_port_range: 22
            access: Allow
            priority: 1000
            direction: Inbound
          - name: 'AllowMyIpAddressCustom9090Inbound'
            protocol: '*'
            source_address_prefix: "{{local_ip}}"
            destination_port_range: '*'
            access: Allow
            priority: 1010
            direction: Inbound
          - name: 'AllowMyIpAddressCustom9100Inbound'
            protocol: '*'
            source_address_prefix: "{{local_ip}}"
            destination_port_range: '*'
            access: Allow
            priority: 1020
            direction: Inbound
          - name: 'AllowMonitorServer9100Inbound'
            protocol: '*'
            source_address_prefix: "20.224.133.66"
            destination_port_range: '*'
            access: Allow
            priority: 1030
            direction: Inbound
      when: local_ip | ipaddr

    - name: "Create a {{nic_root_name}}X network interface for each VM"
      azure_rm_networkinterface:
        name: "{{nic_root_name}}{{item}}"
        resource_group: "{{resourcegroup_name}}"
        virtual_network: "{{virtualnetwork_name}}"
        subnet_name: "{{subnet_name}}"
        security_group: "{{securitygroup_name}}"
        ip_configurations:
          - name: "ipconfig"
            public_ip_address_name: "{{public_ip_name}}{{item}}"
            primary: True
      with_sequence: count="{{instances_number}}"

    - name: "Create a {{project_prefix}}-monitor network interface for monitoring VM"
      azure_rm_networkinterface:
        name: "{{nic_root_name}}-monitor"
        resource_group: "{{resourcegroup_name}}"
        virtual_network: "{{virtualnetwork_name}}"
        subnet_name: "{{subnet_name}}"
        security_group: "{{securitygroup_name}}"
        ip_configurations:
          - name: "ipconfig"
            public_ip_address_name: "{{public_ip_name}}-monitor"
            primary: True
      
    - name: "Create {{vm_root_name}}X VM with existing NIC"
      azure_rm_virtualmachine:
        resource_group: "{{resourcegroup_name}}"
        name: "{{vm_root_name}}{{item}}"
        vm_size: "{{vm_size}}"
        managed_disk_type: "{{managed_disk_type}}"
        admin_username: "{{admin_username}}"
        availability_set: "{{availabilityset_name}}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/aurelien/.ssh/authorized_keys"
            key_data: "{{lookup('file', '{{admin_pub_path}}') }}"
        network_interface_names: "{{nic_root_name}}{{item}}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: "7.5"
          version: latest
        tags: applicationRole=vm
      with_sequence: count="{{instances_number}}"

    - name: "Create {{vm_root_name}} Monitor VM with existing NIC"
      azure_rm_virtualmachine:
        resource_group: "{{resourcegroup_name}}"
        name: "{{project_prefix}}-monitorVM"
        vm_size: "{{vm_size}}"
        managed_disk_type: "{{managed_disk_type}}"
        admin_username: "{{admin_username}}"
        availability_set: "{{availabilityset_name}}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/aurelien/.ssh/authorized_keys"
            key_data: "{{lookup('file', '{{admin_pub_path}}') }}"
        network_interface_names: "{{nic_root_name}}-monitor"
        image:
          offer: debian-10
          publisher: Debian
          sku: "10"
          version: latest
        tags: applicationRole=monitor
      tags: vmmonitor

    - name: "update vars/hostvars"
      shell: "ansible-inventory -i myazure_rm.yml --list > ./vars/hostvars"
