- name: Stop/Launch Azure VM
  hosts: all
  vars_prompt:
    - name: "Stop_or_Launch"
      prompt: "LAUNCH (l) or STOP (s) Vms ?"
      private: no
  
  connection: local
  tasks:
    - name: load vars from vars/vmvars
      ansible.builtin.include_vars:
        file: ./vars/vmvars

    - debug:
        msg: inventory_hostname_short = {{inventory_hostname_short}}

    - debug:
        msg: inventory_hostname = {{inventory_hostname}}

    - debug:
        msg: play_hosts = {{play_hosts}}

    - name: Stop VMs
      azure_rm_virtualmachine:
        resource_group: "{{resourcegroup_name}}"
        name: "{{item}}"
        state: present
        started: false
        admin_username: "{{admin_username}}"
      loop: 
        - "{{inventory_hostname_short}}"
      when: Stop_or_Launch == "s"

    - name: Launch VMs
      azure_rm_virtualmachine:
        resource_group: "{{resourcegroup_name}}"
        name: "{{item}}"
        state: present
        started: true
        admin_username: "{{admin_username}}"
      loop: 
        - "{{inventory_hostname_short}}"
      when: Stop_or_Launch == "l"
